/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_package;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.regex.*;


/**
 *
 * @author Himanshu
 */
public class RegisterationForm extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationForm
     */
    public RegisterationForm() {
        initComponents();
     //   this.setLocationRelativeTo(null);//////////////////////////////////because this is already done in class login when after creation of object of registration form
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlClose = new javax.swing.JLabel();
        jlMinimize = new javax.swing.JLabel();
        jlRegisteration = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlMobile = new javax.swing.JLabel();
        jlPassword = new javax.swing.JLabel();
        jtName = new javax.swing.JTextField();
        jbRegister = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jlName = new javax.swing.JLabel();
        jlFathername = new javax.swing.JLabel();
        jpRePassword = new javax.swing.JPasswordField();
        jtFathername = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPasswordField();
        jlRePassword = new javax.swing.JLabel();
        jPassword2 = new javax.swing.JLabel();
        jlAddress = new javax.swing.JLabel();
        jtAddress = new javax.swing.JTextField();
        jtMobile = new javax.swing.JTextField();
        jlUsername = new javax.swing.JLabel();
        jtUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jlClose.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jlClose.setForeground(new java.awt.Color(255, 255, 255));
        jlClose.setText("X");
        jlClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlCloseMouseClicked(evt);
            }
        });

        jlMinimize.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jlMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jlMinimize.setText("-");
        jlMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlMinimizeMouseClicked(evt);
            }
        });

        jlRegisteration.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jlRegisteration.setForeground(new java.awt.Color(255, 255, 255));
        jlRegisteration.setText("Registration Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlRegisteration)
                .addGap(220, 220, 220)
                .addComponent(jlMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jlClose))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jlClose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlRegisteration)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlMobile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlMobile.setText("Mobile no.");
        jPanel3.add(jlMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 131, -1, -1));

        jlPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlPassword.setText("Password");
        jPanel3.add(jlPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 235, -1, -1));

        jtName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNameActionPerformed(evt);
            }
        });
        jtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNameKeyTyped(evt);
            }
        });
        jPanel3.add(jtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 24, 202, -1));

        jbRegister.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbRegister.setText("Register");
        jbRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegisterActionPerformed(evt);
            }
        });
        jPanel3.add(jbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 479, -1, -1));

        jbCancel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 479, 100, 30));

        jlName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlName.setText("Name");
        jPanel3.add(jlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, -1, -1));

        jlFathername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlFathername.setText("Father's Name");
        jPanel3.add(jlFathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 79, -1, -1));

        jpRePassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jpRePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpRePasswordActionPerformed(evt);
            }
        });
        jPanel3.add(jpRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 284, 202, -1));

        jtFathername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtFathername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFathernameActionPerformed(evt);
            }
        });
        jtFathername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtFathernameKeyTyped(evt);
            }
        });
        jPanel3.add(jtFathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 76, 202, -1));

        jpPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jpPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(jpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 232, 202, -1));

        jlRePassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlRePassword.setText("Retype Password");
        jPanel3.add(jlRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 284, -1, -1));

        jPassword2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel3.add(jPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jlAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlAddress.setText("Delivery Address");
        jPanel3.add(jlAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 336, 154, -1));

        jtAddress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAddressActionPerformed(evt);
            }
        });
        jPanel3.add(jtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 336, 202, 104));

        jtMobile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMobileActionPerformed(evt);
            }
        });
        jtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtMobileKeyTyped(evt);
            }
        });
        jPanel3.add(jtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 128, 202, -1));

        jlUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlUsername.setText("Username");
        jPanel3.add(jlUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 186, -1, -1));

        jtUsername.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsernameActionPerformed(evt);
            }
        });
        jtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtUsernameKeyTyped(evt);
            }
        });
        jPanel3.add(jtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 180, 202, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 90, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jlMinimizeMouseClicked

    private void jlCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlCloseMouseClicked

    private void jtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMobileActionPerformed

    private void jpPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpPasswordActionPerformed

    private void jpRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpRePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpRePasswordActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegisterActionPerformed

       // System.out.println(jtMobile.getText().trim()+"ihdwcghvvdyvhoejvucv");
       /* name=jtName.getText();
        fname=jtFathername.getText();
        /////////////////////////////this is done to avoid numberFormatException
        //mobile=Integer.parseInt(jtMobile.getText().trim());
        //uname=Integer.parseInt(jtUsername.getText());
        pass=String.valueOf(jpPassword.getPassword());
        repass=String.valueOf(jpRePassword.getPassword());
        address=jtAddress.getText();*/
        //this.setVisible(false);
        
        if(jtName.getText().trim().isEmpty() || jtFathername.getText().trim().isEmpty() || jtMobile.getText().trim().isEmpty() || jtUsername.getText().trim().isEmpty() || jpPassword.getText().trim().isEmpty() || jpRePassword.getText().trim().isEmpty() || jtAddress.getText().trim().isEmpty()){
            /////////////////////////////mobile is converted to string because it is showing error"int cannot be deferenced"
            /////////////////////////////this error occurs n=because mobile is an int value and not an abject so how can it calls a function if it is not an object   
            this.setVisible(false);
            JOptionPane.showMessageDialog(null,"One or more field(s) is(are) empty.");
            this.setVisible(true);
        }
        else{
            Pattern p=Pattern.compile("^[7-9][0-9]{9}$");
            Matcher m=p.matcher(jtMobile.getText());
            Pattern q=Pattern.compile("^[1][5-8][00100]{5}[1-9][0][0-9]{2}");
            Matcher n=q.matcher(jtUsername.getText()); 
            if(!m.matches())
            {
                JOptionPane.showMessageDialog(null,"Invalid mobile number");
                jtMobile.setText("");
            }
             if(!n.matches())
            {
                JOptionPane.showMessageDialog(null,"Invalid username");
                jtUsername.setText("");
            }
            if( (jpPassword.getText().equals(jpRePassword.getText())) && m.matches() && n.matches()){
                try{///////////////////////////////////Inserting  data into database 
                Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://localhost:3306/xyz";
                String username="root";
                String password="zxcv";
                String query="insert into student values(?,?,?,?,?,?)";
                Connection con=DriverManager.getConnection(url, username, password);
                PreparedStatement pst=con.prepareStatement(query);
                pst.setString(1,jtUsername.getText());
                pst.setString(2,jtFathername.getText());
                pst.setString(3,jtName.getText());
                pst.setString(4,jtMobile.getText());
                pst.setString(5,jpPassword.getText());
                pst.setString(6,jtAddress.getText());
                int count=pst.executeUpdate();
                System.out.println(count +" row/s affected");
                pst.close();
                con.close();
                
                this.dispose();
                JOptionPane.showMessageDialog(null,"Registeration Successful");
                Login login=new Login();
                login.setVisible(true);
                login.pack();
                login.setLocationRelativeTo(null);
                login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                }catch(Exception e){
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null,e);
                    this.setVisible(true);
                }
            }
            else if(!jpPassword.getText().equals(jpRePassword.getText())){
                this.setVisible(false);
                JOptionPane.showMessageDialog(null,"Please confirm you've entered your password correctly.","Unsuccessful!",JOptionPane.ERROR_MESSAGE);
                this.setVisible(true);
                //jtName.setText("");
                //jtFathername.setText("");
                //jtMobile.setText("");
                //jtUsername.setText("");
                jpPassword.setText("");
                jpRePassword.setText("");
                //jtAddress.setText("");
            }
        }
       /* else{
            JOptionPane.showMessageDialog(null,"Registeration Unsuccessful!","Unsuccessful!",JOptionPane.ERROR);
        }
        ////////////////this is made to know that value can be passed in constructor of main to have value of object of this class
        new Main(fname,lname,mobile,uname,pass,repass,address);
       */
      //  this.dispose();
    }//GEN-LAST:event_jbRegisterActionPerformed

    private void jtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNameActionPerformed

    private void jtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAddressActionPerformed

    private void jtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsernameActionPerformed

    private void jtFathernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFathernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFathernameActionPerformed

    private void jtMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMobileKeyTyped
        //////////////////////////to restrict entering characters
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtMobileKeyTyped

    private void jtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsernameKeyTyped
         //////////////////////////to restrict entering characters
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtUsernameKeyTyped

    private void jtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNameKeyTyped
         //////////////////////////to restrict entering characters
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE)){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_jtNameKeyTyped

    private void jtFathernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFathernameKeyTyped
         //////////////////////////to restrict entering characters
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE)){
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_jtFathernameKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
         Login login=new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterationForm().setVisible(true);
            }
        });
    }
    
  //  private String name=null,fname=null,pass=null,repass=null,address=null;
   // private int  uname,mobile;
    ///////////////////////////this is done to access value of this object in another class but when object is made in another class then that object is new object and it has only null values  
    /*  public String getname() {
        return name;
    }

    public String getFname() {
        return fname;
    }

    public int getMobile() {
        return mobile;
    }

    public int getUname() {
        return uname;
    }

    public String getPass() {
        return pass;
    }

    public String getRepass() {
        return repass;
    }

    public String getAddress() {
        return address;
    }    
*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jPassword2;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbRegister;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlClose;
    private javax.swing.JLabel jlFathername;
    private javax.swing.JLabel jlMinimize;
    private javax.swing.JLabel jlMobile;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlRePassword;
    private javax.swing.JLabel jlRegisteration;
    private javax.swing.JLabel jlUsername;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JPasswordField jpRePassword;
    private javax.swing.JTextField jtAddress;
    private javax.swing.JTextField jtFathername;
    private javax.swing.JTextField jtMobile;
    private javax.swing.JTextField jtName;
    private javax.swing.JTextField jtUsername;
    // End of variables declaration//GEN-END:variables
}
